"use client"

import * as React from "react"
import { Sparkles, ExternalLink, ArrowRight } from "lucide-react"
import { AgentCard, MetricBlock } from "./agent-card"
import { Button } from "@/components/ui/button"
import { Expandable } from "@/components/ui/expandable"

type MlProblem = {
  id: string
  name: string
  engine: "autogluon" | "autorag"
  category: string
  autogluon_task_type?: string | null
  autorag_task_type?: string | null
  business_kpis: string[]
}

type ExaInsight = {
  title: string
  url: string
  snippet: string
}

export type DecomposerCardData = {
  use_cases_mapped: number
  projected_roi?: string
  ml_problems: MlProblem[]
  exa_insights?: Record<string, ExaInsight[]>
  constraint_summary?: { narrative?: string }
}

function taskTypeLabel(p: MlProblem): string {
  const t = p.autogluon_task_type ?? p.autorag_task_type ?? ""
  if (t.includes("classification")) return "Classification"
  if (t.includes("regression")) return "Regression"
  if (t.includes("time_series")) return "Time Series"
  if (t.includes("rag") || t.includes("retrieval") || t.includes("qa")) return "Retrieval"
  return p.engine === "autorag" ? "Retrieval" : "ML Model"
}

export function DecomposerCard({
  cardData,
  onConfirm,
  onAdjust,
  loading = false,
}: {
  cardData: DecomposerCardData
  onConfirm?: () => void
  onAdjust?: () => void
  loading?: boolean
}) {
  const { ml_problems = [], use_cases_mapped, projected_roi, exa_insights = {} } = cardData
  const roiDisplay = projected_roi ? projected_roi.slice(0, 24) : "—"

  return (
    <AgentCard
      title="AI Strategy Generated"
      status="complete"
      icon={Sparkles}
      source="Generated by Strategy Agent using LLM + Exa enrichment"
    >
      <p className="text-sm leading-relaxed text-muted-foreground">
        Based on your business problem, I identified{" "}
        <span className="font-medium text-foreground">{use_cases_mapped} solvable ML use cases</span>.
        {projected_roi ? ` ${projected_roi}` : ""}
      </p>

      <div className="mt-4 grid grid-cols-2 gap-2.5 sm:grid-cols-3">
        <MetricBlock label="Use cases mapped" value={String(use_cases_mapped)} tone="primary" />
        <MetricBlock label="Projected ROI" value={roiDisplay} tone="success" hint="LLM estimate" />
        <MetricBlock label="Feasibility" value="High" tone="success" hint="Data available" />
      </div>

      <div className="mt-4 overflow-hidden rounded-lg border border-border">
        <table className="w-full text-left text-sm">
          <thead className="bg-surface-muted text-[11px] uppercase tracking-wide text-muted-foreground">
            <tr>
              <th className="px-3 py-2 font-medium">Use Case</th>
              <th className="px-3 py-2 font-medium">Task Type</th>
              <th className="hidden px-3 py-2 font-medium sm:table-cell">Projected ROI</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border">
            {ml_problems.map((p) => (
              <tr key={p.id} className="hover:bg-surface-muted/50">
                <td className="px-3 py-2.5">
                  <div className="font-medium text-foreground">{p.name}</div>
                  <div className="text-[11px] text-muted-foreground">
                    {p.engine === "autorag" ? "GenAI" : "Predictive"}
                  </div>
                </td>
                <td className="px-3 py-2.5">
                  <span className="rounded-md bg-info-soft px-2 py-0.5 text-[11px] font-medium text-primary">
                    {taskTypeLabel(p)}
                  </span>
                </td>
                <td className="hidden px-3 py-2.5 text-xs text-muted-foreground sm:table-cell">
                  {p.business_kpis.slice(0, 2).join(" · ") || "—"}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {ml_problems.map((p) => {
        const insights = exa_insights[p.id] ?? []
        if (!insights.length) return null
        return (
          <Expandable key={p.id} label={`Evidence for ${p.name}`} className="mt-2">
            <ul className="space-y-3">
              {insights.map((ins, i) => (
                <li key={i} className="text-[13px] text-muted-foreground">
                  {ins.snippet && <p className="leading-relaxed">{ins.snippet}</p>}
                  {ins.url && (
                    <a
                      href={ins.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="mt-1 inline-flex items-center gap-1 text-[11px] text-primary hover:underline"
                    >
                      <ExternalLink className="h-3 w-3" aria-hidden="true" />
                      {ins.title || ins.url}
                    </a>
                  )}
                </li>
              ))}
            </ul>
          </Expandable>
        )
      })}

      <div className="mt-4 flex flex-wrap items-center gap-2">
        <Button onClick={onConfirm} disabled={loading}>
          Confirm strategy
          <ArrowRight className="h-4 w-4" aria-hidden="true" />
        </Button>
        <Button variant="outline" onClick={onAdjust} disabled={loading}>
          Adjust use cases
        </Button>
      </div>
    </AgentCard>
  )
}
