from __future__ import annotations

import importlib.metadata
import json
import os
import shutil
import tempfile
import zipfile
from pathlib import Path
from typing import Any


_HEAVY_FAMILIES = {"NN_TORCH", "FASTAI"}
_FAMILY_PKG_MAP = {
    "GBM": "lightgbm",
    "CAT": "catboost",
    "XGB": "xgboost",
    "RF": None,
    "XT": None,
    "KNN": None,
    "LR": None,
    "NN_TORCH": "torch",
    "FASTAI": "fastai",
}


def assemble(out_dir: Path, files: dict[str, str | bytes | Path]) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    for rel_path, content in files.items():
        dest = out_dir / rel_path
        dest.parent.mkdir(parents=True, exist_ok=True)
        if isinstance(content, Path):
            if content.is_dir():
                shutil.copytree(str(content), str(dest), dirs_exist_ok=True)
            else:
                shutil.copy2(str(content), str(dest))
        elif isinstance(content, bytes):
            dest.write_bytes(content)
        else:
            dest.write_text(content, encoding="utf-8")


def pin_requirements(engine_families: list[str]) -> str:
    base_pkgs = ["autogluon-tabular"]
    extra_pkgs = []
    for family in engine_families:
        pkg = _FAMILY_PKG_MAP.get(family.upper())
        if pkg:
            extra_pkgs.append(pkg)

    lines: list[str] = []
    for pkg in base_pkgs + extra_pkgs:
        try:
            version = importlib.metadata.version(pkg)
            lines.append(f"{pkg}=={version}")
        except importlib.metadata.PackageNotFoundError:
            lines.append(f"# {pkg} not installed in current env")

    return "\n".join(lines) + "\n"


def pin_requirements_autorag() -> str:
    pkgs = ["AutoRAG", "openai", "pandas", "pyarrow"]
    lines: list[str] = []
    for pkg in pkgs:
        try:
            version = importlib.metadata.version(pkg)
            lines.append(f"{pkg}=={version}")
        except importlib.metadata.PackageNotFoundError:
            lines.append(f"# {pkg} not installed in current env")
    return "\n".join(lines) + "\n"


def render_readme(
    narrative: Any,
    manifest: Any,
    commands: dict[str, str],
    engine_families: list[str] | None = None,
    run_context: dict[str, Any] | None = None,
) -> str:
    metric_val = manifest.primary_metric_value
    metric_str = f"{metric_val:.6f}" if metric_val is not None else "N/A"
    secondary_rows = "\n".join(
        f"| {k} | {v if v is not None else 'N/A'} |"
        for k, v in _ordered_secondary_metrics(
            manifest.engine_type,
            manifest.primary_metric,
            manifest.secondary_metrics or {},
        )
    )
    caveat_lines = "\n".join(f"- {c}" for c in (narrative.caveats or []))
    families_note = f"\nModel families used: `{', '.join(engine_families)}`" if engine_families else ""

    infer_cmd = commands.get("infer", "python infer.py --input sample_input.json")
    train_cmd = commands.get("train", "python train.py --dataset your_dataset.csv --target <col>")
    serve_cmd = commands.get("serve", "uvicorn server:app --host 0.0.0.0 --port 8080")

    run_section = _render_run_context_section(run_context, manifest) if run_context else ""
    api_usage_section = _render_api_usage_section(manifest.engine_type)

    return f"""# VectorForge Artifact — {manifest.engine_type}

## Overview

{narrative.overview}

{run_section}

## Metrics

| Metric | Value |
|--------|-------|
| {manifest.primary_metric} | {metric_str} |
{secondary_rows}
{families_note}

## Quick Start

```bash
# Install dependencies
pip install -r requirements.txt

# Run inference (CLI)
{infer_cmd}

# Start FastAPI server
{serve_cmd}

# Retrain
{train_cmd}
```

{api_usage_section}

## CLI Usage

```python
import json
from model_interface import load_model

with open("sample_input.json", encoding="utf-8") as f:
    payload = json.load(f)

model = load_model()
predictions = model.predict(payload)
print(predictions)
print(model.metadata)
```

## Walkthrough

{narrative.usage_walkthrough}

## Serving Notes

{narrative.serving_notes}

## Deployment

```bash
# Build Docker image, push to ECR, deploy via CloudFormation
chmod +x deploy.sh
./deploy.sh
```

See `cloudformation.yaml` for the full AWS App Runner stack definition.

## Retraining Notes

{narrative.retraining_notes}

## Caveats

{caveat_lines}

---
*Generated by VectorForge artifact_forge. Engine: `{manifest.engine_type}`*
"""


def _render_api_usage_section(engine_type: str) -> str:
    if engine_type == "autorag":
        payload_key = "queries"
        sample_payload = '{"queries": ["What is covered in this document?"]}'
    else:
        payload_key = "instances"
        sample_payload = '{"instances": [{"feature_1": 0.0, "feature_2": "value"}]}'

    return f"""## API Usage

```bash
# Health check
curl http://localhost:8080/health

# Predict
curl -X POST http://localhost:8080/predict \\
  -H "Content-Type: application/json" \\
  -d '{sample_payload}'

# Interactive docs
open http://localhost:8080/docs
```

```python
import json
import requests

with open("sample_input.json", encoding="utf-8") as f:
    sample_input = json.load(f)

resp = requests.post(
    "http://localhost:8080/predict",
    json={{{payload_key!r}: sample_input}},
)
print(resp.json())
```"""


def _render_run_context_section(ctx: dict[str, Any], manifest: Any) -> str:
    parts: list[str] = ["## Run Context\n"]
    parts += _render_problem_section(ctx.get("user_request", {}))
    parts += _render_dataset_section(ctx.get("dataset_profile", {}))
    parts += _render_metric_section(ctx.get("metric_decision", {}))
    parts += _render_experiments_section(ctx.get("all_experiments", []), manifest)
    parts += _render_winner_section(ctx.get("winner", {}), ctx.get("final_recommendation", {}))
    return "\n".join(parts)


def _render_problem_section(req: dict[str, Any]) -> list[str]:
    if not req:
        return []
    problem = (
        req.get("problem_statement")
        or req.get("description")
        or req.get("document_description")
        or req.get("optimization_goal")
    )
    parts: list[str] = []
    if problem:
        parts = ["### Problem Statement\n", f"{problem}\n"]

    optimization_goal = req.get("optimization_goal")
    if optimization_goal and optimization_goal != problem:
        if not parts:
            parts = ["### Problem Statement\n"]
        parts.append(f"\n**Optimization goal:** {optimization_goal}\n")

    kpis = req.get("business_kpis") or req.get("business_kpi")
    if kpis:
        if isinstance(kpis, list):
            kpi_text = "; ".join(str(kpi) for kpi in kpis)
        else:
            kpi_text = str(kpis)
        if not parts:
            parts = ["### Problem Statement\n"]
        parts.append(f"\n**Business KPI:** {kpi_text}\n")

    if req.get("target_column"):
        if not parts:
            parts = ["### Problem Statement\n"]
        parts.append(f"\n**Target column:** `{req['target_column']}`\n")
    if req.get("rounds") or req.get("architectures_per_round"):
        if not parts:
            parts = ["### Problem Statement\n"]
        rounds = req.get("rounds", "N/A")
        architectures = req.get("architectures_per_round", "N/A")
        parts.append(f"\n**Search budget:** {rounds} rounds, {architectures} architectures per round\n")
    return parts


def _render_dataset_section(profile: dict[str, Any]) -> list[str]:
    if not profile:
        return []
    ds = profile.get("dataset", {})
    feat = profile.get("features", {})
    tgt = profile.get("target", {})
    parts: list[str] = ["\n### Dataset Profile\n"]
    detail_count = 0
    if ds:
        parts.append(f"- Rows: {ds.get('rows', 'N/A')} | Columns: {ds.get('columns', 'N/A')}")
        parts.append(f"- Missing cells ratio: {ds.get('missing_cells_ratio', 0):.1%}\n")
        detail_count += 1
    if feat:
        parts.append(f"- Numeric features: {feat.get('numeric_count', 'N/A')}")
        parts.append(f"- Categorical features: {feat.get('categorical_count', 'N/A')}\n")
        detail_count += 1
    if tgt:
        parts.append(f"- Target `{tgt.get('name', 'target')}` distribution: {tgt.get('class_distribution', {})}\n")
        detail_count += 1

    if profile.get("file_count") is not None:
        parts.append(f"- Documents: {profile.get('file_count', 'N/A')}")
        detail_count += 1
    if profile.get("extensions"):
        ext_summary = ", ".join(f"{ext}: {count}" for ext, count in profile["extensions"].items())
        parts.append(f"- File types: {ext_summary}")
        detail_count += 1
    if profile.get("human_document_description"):
        parts.append(f"- Description: {profile['human_document_description']}")
        detail_count += 1

    available_parse = [
        item.get("method")
        for item in profile.get("no_api_parse_catalog", [])
        if item.get("available") and item.get("method")
    ][:4]
    if available_parse:
        parts.append(f"- Available parsers: {', '.join(available_parse)}")
        detail_count += 1

    available_chunkers = [
        item.get("method")
        for item in profile.get("no_api_chunk_catalog", [])
        if item.get("available") and item.get("method")
    ][:4]
    if available_chunkers:
        parts.append(f"- Available chunkers: {', '.join(available_chunkers)}\n")
        detail_count += 1

    return parts if detail_count else []


def _render_metric_section(metric_dec: dict[str, Any]) -> list[str]:
    if not metric_dec:
        return []
    parts = ["\n### Metric Selection Rationale\n"]
    parts.append(f"{metric_dec.get('reasoning', '')}\n")
    parts.append(f"\n**Primary metric:** `{metric_dec.get('selected_primary_metric', 'N/A')}`")
    secondaries = metric_dec.get("secondary_metrics", [])
    if secondaries:
        parts.append(f"  |  **Secondary:** {', '.join(f'`{m}`' for m in secondaries)}\n")
    return parts


def _render_experiments_section(experiments: list[dict[str, Any]], manifest: Any) -> list[str]:
    if not experiments:
        return []
    metric_names = _experiment_metric_columns(experiments, manifest)
    parts = ["\n### Experiment History\n"]
    parts.append("| Experiment | " + " | ".join(_metric_label(name) for name in metric_names) + " |")
    parts.append("|---|" + "|".join("---" for _ in metric_names) + "|")
    for exp in experiments:
        eid = exp.get("_experiment_path", "?").split("/")[-1]
        values = [_format_metric_value(_metric_value(exp, name)) for name in metric_names]
        parts.append(f"| `{eid}` | " + " | ".join(values) + " |")
    parts.append("")
    return parts


def _render_winner_section(winner: dict[str, Any], rec: dict[str, Any]) -> list[str]:
    if not winner and not rec:
        return []
    exp_id = (
        winner.get("experiment_id")
        or winner.get("best_experiment_id")
        or rec.get("best_experiment_id", "N/A")
    )
    why = winner.get("why_selected") or rec.get("why_selected", "Highest primary metric across all completed experiments.")
    return ["\n### Winning Experiment\n", f"**`{exp_id}`** — {why}\n"]


def _experiment_metric_columns(experiments: list[dict[str, Any]], manifest: Any) -> list[str]:
    metric_names: list[str] = []

    def add(name: Any) -> None:
        if name and name != "unknown" and name not in metric_names:
            metric_names.append(str(name))

    engine_type = getattr(manifest, "engine_type", "")
    primary_metric = getattr(manifest, "primary_metric", None)
    secondary_metrics = getattr(manifest, "secondary_metrics", {}) or {}

    for name in _canonical_metric_order(engine_type):
        if name == primary_metric or name in secondary_metrics or _experiments_include_metric(experiments, name):
            add(name)

    add(primary_metric)
    for name in secondary_metrics.keys():
        add(name)

    if not metric_names:
        for exp in experiments:
            add(exp.get("primary_metric"))
            for source in (exp.get("evaluation", {}), exp.get("secondary_metrics", {})):
                for name in source.keys():
                    add(name)
            if metric_names:
                break

    return metric_names or ["primary_metric_value"]


def _ordered_secondary_metrics(
    engine_type: str,
    primary_metric: str,
    secondary_metrics: dict[str, Any],
) -> list[tuple[str, Any]]:
    ordered: list[tuple[str, Any]] = []
    seen: set[str] = set()
    for name in _canonical_metric_order(engine_type):
        if name != primary_metric and name in secondary_metrics:
            ordered.append((name, secondary_metrics[name]))
            seen.add(name)
    for name, value in secondary_metrics.items():
        if name not in seen:
            ordered.append((name, value))
    return ordered


def _canonical_metric_order(engine_type: str) -> list[str]:
    if engine_type == "autorag":
        return ["retrieval_f1", "retrieval_recall", "retrieval_precision", "rouge", "g_eval"]
    if engine_type == "autogluon_tabular":
        return ["roc_auc", "accuracy", "balanced_accuracy", "mcc", "f1", "precision", "recall"]
    return []


def _experiments_include_metric(experiments: list[dict[str, Any]], metric_name: str) -> bool:
    return any(_metric_value(exp, metric_name) is not None for exp in experiments)


def _metric_value(exp: dict[str, Any], metric_name: str) -> Any:
    if metric_name == exp.get("primary_metric") and "primary_metric_value" in exp:
        return exp.get("primary_metric_value")
    for source in (exp.get("evaluation", {}), exp.get("secondary_metrics", {}), exp):
        if metric_name in source:
            return source[metric_name]
    if metric_name == "primary_metric_value":
        return exp.get("primary_metric_value")
    return None


def _metric_label(metric_name: str) -> str:
    labels = {
        "accuracy": "Accuracy",
        "balanced_accuracy": "Balanced Accuracy",
        "f1": "F1",
        "g_eval": "G-Eval",
        "mcc": "MCC",
        "precision": "Precision",
        "recall": "Recall",
        "retrieval_f1": "Retrieval F1",
        "retrieval_precision": "Retrieval Precision",
        "retrieval_recall": "Retrieval Recall",
        "roc_auc": "ROC AUC",
        "rouge": "ROUGE",
    }
    return labels.get(metric_name, metric_name.replace("_", " ").title())


def _format_metric_value(value: Any) -> str:
    if value is None:
        return "N/A"
    if isinstance(value, (int, float)):
        return f"{value:.4f}"
    return str(value)


def render_server(task_type: str) -> str:
    return f'''"""
server.py — FastAPI inference server.
Generated by VectorForge artifact_forge.

Usage:
    uvicorn server:app --host 0.0.0.0 --port 8080 --reload
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

from model_interface import load_model


app = FastAPI(
    title="VectorForge Inference API",
    description="Inference endpoint for task: {task_type}",
    version="1.0.0",
)

_model = None


def _get_model():
    global _model
    if _model is None:
        _model = load_model()
    return _model


class PredictRequest(BaseModel):
    instances: list[dict[str, Any]]


class PredictResponse(BaseModel):
    predictions: list[Any]
    count: int
    task: str = "{task_type}"


@app.get("/health")
def health():
    return {{"status": "ok", "task": "{task_type}"}}


@app.get("/metadata")
def metadata():
    return _get_model().metadata


@app.post("/predict", response_model=PredictResponse)
def predict(request: PredictRequest):
    if not request.instances:
        raise HTTPException(status_code=422, detail="instances must be a non-empty list")
    try:
        predictions = _get_model().predict(request.instances)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc
    return PredictResponse(predictions=predictions, count=len(predictions))


# Allow posting a raw JSON array directly (convenience wrapper)
@app.post("/predict/raw")
def predict_raw(instances: list[dict[str, Any]]):
    if not instances:
        raise HTTPException(status_code=422, detail="instances must be a non-empty list")
    try:
        predictions = _get_model().predict(instances)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc
    return {{"predictions": predictions, "count": len(predictions)}}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("server:app", host="0.0.0.0", port=8080, reload=False)
'''


def render_dockerfile() -> str:
    return '''\
FROM python:3.12-slim

WORKDIR /app

# Install system dependencies needed by autogluon
RUN apt-get update && apt-get install -y --no-install-recommends \\
    libgomp1 \\
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \\
    && pip install --no-cache-dir fastapi uvicorn[standard]

COPY . .

EXPOSE 8080

# Warm up model on startup via module load
ENV PYTHONUNBUFFERED=1

CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8080", "--workers", "1"]
'''


def render_deploy_sh(run_id: str) -> str:
    safe_id = run_id.replace("_", "-").lower()
    return f'''\
#!/usr/bin/env bash
# deploy.sh — Build, push to ECR, then trigger CloudFormation deploy.
# Usage: AWS_ACCOUNT_ID=123456789012 AWS_REGION=us-east-1 ./deploy.sh
set -euo pipefail

: "${{AWS_ACCOUNT_ID:?Set AWS_ACCOUNT_ID}}"
: "${{AWS_REGION:?Set AWS_REGION}}"

APP_NAME="{safe_id}"
ECR_REPO="${{AWS_ACCOUNT_ID}}.dkr.ecr.${{AWS_REGION}}.amazonaws.com/${{APP_NAME}}"
IMAGE_TAG="$(date +%Y%m%d%H%M%S)"
IMAGE_URI="${{ECR_REPO}}:${{IMAGE_TAG}}"
STACK_NAME="vf-${{APP_NAME}}"

echo ">>> Authenticating to ECR..."
aws ecr get-login-password --region "${{AWS_REGION}}" \\
  | docker login --username AWS --password-stdin "${{ECR_REPO}}"

echo ">>> Creating ECR repository (idempotent)..."
aws ecr describe-repositories --repository-names "${{APP_NAME}}" --region "${{AWS_REGION}}" >/dev/null 2>&1 \\
  || aws ecr create-repository --repository-name "${{APP_NAME}}" --region "${{AWS_REGION}}"

echo ">>> Building Docker image..."
docker build -t "${{APP_NAME}}:${{IMAGE_TAG}}" .

echo ">>> Tagging and pushing..."
docker tag "${{APP_NAME}}:${{IMAGE_TAG}}" "${{IMAGE_URI}}"
docker push "${{IMAGE_URI}}"

echo ">>> Deploying CloudFormation stack: ${{STACK_NAME}}..."
aws cloudformation deploy \\
  --stack-name "${{STACK_NAME}}" \\
  --template-file cloudformation.yaml \\
  --parameter-overrides \\
    ImageUri="${{IMAGE_URI}}" \\
    AppName="${{APP_NAME}}" \\
  --capabilities CAPABILITY_IAM \\
  --region "${{AWS_REGION}}"

echo ">>> Deployed. Service URL:"
aws cloudformation describe-stacks \\
  --stack-name "${{STACK_NAME}}" \\
  --region "${{AWS_REGION}}" \\
  --query "Stacks[0].Outputs[?OutputKey==\\'ServiceUrl\\'].OutputValue" \\
  --output text
'''


def render_cloudformation(run_id: str) -> str:
    safe_id = run_id.replace("_", "-").lower()
    return f'''\
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  VectorForge inference service — {run_id}
  Deploys a containerized FastAPI model server on AWS App Runner.

Parameters:
  ImageUri:
    Type: String
    Description: Full ECR image URI including tag (e.g. 123456789012.dkr.ecr.us-east-1.amazonaws.com/my-app:20260609)
  AppName:
    Type: String
    Default: "{safe_id}"
    Description: Name for the App Runner service and IAM role.
  Cpu:
    Type: String
    Default: "1 vCPU"
    AllowedValues: ["0.25 vCPU", "0.5 vCPU", "1 vCPU", "2 vCPU", "4 vCPU"]
  Memory:
    Type: String
    Default: "2 GB"
    AllowedValues: ["0.5 GB", "1 GB", "2 GB", "3 GB", "4 GB", "6 GB", "8 GB", "10 GB", "12 GB"]

Resources:

  # IAM role that lets App Runner pull from ECR
  AppRunnerECRAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${{AppName}}-apprunner-ecr-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: build.apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess

  InferenceService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Ref AppName
      SourceConfiguration:
        AuthenticationConfiguration:
          AccessRoleArn: !GetAtt AppRunnerECRAccessRole.Arn
        ImageRepository:
          ImageIdentifier: !Ref ImageUri
          ImageRepositoryType: ECR
          ImageConfiguration:
            Port: "8080"
            RuntimeEnvironmentVariables:
              - Name: PYTHONUNBUFFERED
                Value: "1"
        AutoDeploymentsEnabled: false
      InstanceConfiguration:
        Cpu: !Ref Cpu
        Memory: !Ref Memory
      HealthCheckConfiguration:
        Protocol: HTTP
        Path: /health
        Interval: 10
        Timeout: 5
        HealthyThreshold: 2
        UnhealthyThreshold: 3
      Tags:
        - Key: ManagedBy
          Value: VectorForge
        - Key: RunId
          Value: "{run_id}"

Outputs:
  ServiceUrl:
    Description: App Runner service URL (HTTPS)
    Value: !Sub "https://${{InferenceService.ServiceUrl}}"
  ServiceArn:
    Description: App Runner service ARN
    Value: !GetAtt InferenceService.ServiceArn
'''


def render_server_rag(task_type: str = "rag_optimization") -> str:
    return f'''"""
server.py — FastAPI RAG inference server.
Generated by VectorForge artifact_forge.

Usage:
    OPENAI_API_KEY=... uvicorn server:app --host 0.0.0.0 --port 8080 --reload

Environment variables:
    OPENAI_API_KEY   Required — passed to OpenAI at runtime.
"""
from __future__ import annotations

import os
from typing import Any

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

from model_interface import load_model


app = FastAPI(
    title="VectorForge RAG Inference API",
    description="Query endpoint for task: {task_type}",
    version="1.0.0",
)

_model = None


def _configure_openai_environment() -> None:
    api_key = (
        os.environ.get("OPENAI_API_KEY")
        or os.environ.get("VECTORFORGE_OPENAI_API_KEY")
        or os.environ.get("OPENAI_KEY")
    )
    if not api_key:
        raise RuntimeError(
            "OPENAI_API_KEY, VECTORFORGE_OPENAI_API_KEY, or OPENAI_KEY "
            "environment variable is required"
        )
    os.environ["OPENAI_API_KEY"] = api_key
    os.environ["OPENAI_BASE_URL"] = "https://api.openai.com/v1"


def _get_model():
    global _model
    if _model is None:
        _configure_openai_environment()
        _model = load_model()
    return _model


class QueryRequest(BaseModel):
    queries: list[str]


class QueryResult(BaseModel):
    query: str
    answer: str
    contexts: list[str] = []


class QueryResponse(BaseModel):
    results: list[QueryResult]
    count: int
    task: str = "{task_type}"


@app.get("/health")
def health():
    return {{"status": "ok", "task": "{task_type}"}}


@app.get("/metadata")
def metadata():
    return _get_model().metadata


@app.post("/predict", response_model=QueryResponse)
def predict(request: QueryRequest):
    if not request.queries:
        raise HTTPException(status_code=422, detail="queries must be a non-empty list")
    try:
        raw = _get_model().predict(request.queries)
    except RuntimeError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc
    results = [
        QueryResult(
            query=r.get("query", ""),
            answer=r.get("answer", ""),
            contexts=r.get("contexts", []),
        )
        for r in (raw if isinstance(raw, list) else [])
    ]
    return QueryResponse(results=results, count=len(results))


# Convenience: accept raw list of query strings
@app.post("/predict/raw")
def predict_raw(queries: list[str]):
    if not queries:
        raise HTTPException(status_code=422, detail="queries must be a non-empty list")
    try:
        raw = _get_model().predict(queries)
    except RuntimeError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc
    return {{"results": raw, "count": len(raw)}}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("server:app", host="0.0.0.0", port=8080, reload=False)
'''


def render_cloudformation_rag(run_id: str) -> str:
    safe_id = run_id.replace("_", "-").lower()
    return f'''\
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  VectorForge RAG inference service — {run_id}
  Deploys a containerized FastAPI RAG server on AWS App Runner.
  OPENAI_API_KEY is stored in SSM Parameter Store and injected at runtime.

Parameters:
  ImageUri:
    Type: String
    Description: Full ECR image URI including tag
  AppName:
    Type: String
    Default: "{safe_id}"
  OpenAIApiKeyParam:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/vectorforge/{safe_id}/openai-api-key"
    Description: >
      SSM Parameter Store path holding the OpenAI API key.
      Create it first:
        aws ssm put-parameter --name /vectorforge/{safe_id}/openai-api-key \\
          --value "..." --type SecureString
  Cpu:
    Type: String
    Default: "1 vCPU"
    AllowedValues: ["0.25 vCPU", "0.5 vCPU", "1 vCPU", "2 vCPU", "4 vCPU"]
  Memory:
    Type: String
    Default: "2 GB"
    AllowedValues: ["0.5 GB", "1 GB", "2 GB", "3 GB", "4 GB", "6 GB", "8 GB", "10 GB", "12 GB"]

Resources:

  AppRunnerECRAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${{AppName}}-apprunner-ecr-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: build.apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess

  RagInferenceService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Ref AppName
      SourceConfiguration:
        AuthenticationConfiguration:
          AccessRoleArn: !GetAtt AppRunnerECRAccessRole.Arn
        ImageRepository:
          ImageIdentifier: !Ref ImageUri
          ImageRepositoryType: ECR
          ImageConfiguration:
            Port: "8080"
            RuntimeEnvironmentVariables:
              - Name: PYTHONUNBUFFERED
                Value: "1"
              - Name: OPENAI_API_KEY
                Value: !Ref OpenAIApiKeyParam
        AutoDeploymentsEnabled: false
      InstanceConfiguration:
        Cpu: !Ref Cpu
        Memory: !Ref Memory
      HealthCheckConfiguration:
        Protocol: HTTP
        Path: /health
        Interval: 10
        Timeout: 5
        HealthyThreshold: 2
        UnhealthyThreshold: 3
      Tags:
        - Key: ManagedBy
          Value: VectorForge
        - Key: RunId
          Value: "{run_id}"
        - Key: Engine
          Value: autorag

Outputs:
  ServiceUrl:
    Description: App Runner RAG service URL (HTTPS)
    Value: !Sub "https://${{RagInferenceService.ServiceUrl}}"
  ServiceArn:
    Description: App Runner service ARN
    Value: !GetAtt RagInferenceService.ServiceArn
'''


def render_metrics_md(manifest: Any) -> str:
    metric_val = manifest.primary_metric_value
    metric_str = f"{metric_val:.6f}" if metric_val is not None else "N/A"
    rows = "\n".join(
        f"| {k} | {v if v is not None else 'N/A'} |"
        for k, v in (manifest.secondary_metrics or {}).items()
    )
    return f"""# Metrics

| Metric | Value |
|--------|-------|
| {manifest.primary_metric} (primary) | {metric_str} |
{rows}

Trained at: `{manifest.trained_at}`
Smoke status: `{manifest.smoke_status}`
"""


def atomic_write_json(path: Path, payload: Any) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            json.dump(payload, handle, indent=2, sort_keys=True, default=str)
            handle.write("\n")
        os.replace(temp_name, path)
    finally:
        if os.path.exists(temp_name):
            os.unlink(temp_name)
    return path


def seal_zip(package_dir: Path) -> Path:
    zip_path = package_dir.parent / f"{package_dir.name}.zip"
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for file_path in sorted(package_dir.rglob("*")):
            if file_path.is_file():
                zf.write(file_path, file_path.relative_to(package_dir.parent))
    return zip_path
